# Generated by Django 3.2.7 on 2021-09-05 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(blank=True, max_length=50, verbose_name='Plate Number')),
                ('offence', models.CharField(max_length=50, verbose_name='Offence')),
                ('image', models.ImageField(height_field=600, upload_to='uploads/%Y/%m/%d/', verbose_name='Image', width_field=600)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('plate_number', models.CharField(max_length=50, verbose_name='Plate Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Citizen')),
            ],
        ),
    ]
