# Generated by Django 3.2.7 on 2021-09-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license_plate_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='license_plate_recognition.profile', verbose_name='User Details'),
        ),
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
    ]
