# Generated by Django 3.2.7 on 2021-09-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_plate_recognition', '0002_auto_20210906_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='offence',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Offence'),
        ),
    ]
