# Generated by Django 3.2.7 on 2021-09-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_plate_recognition', '0003_alter_log_offence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='offence',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Offence'),
        ),
        migrations.AlterField(
            model_name='log',
            name='plate_number',
            field=models.CharField(blank=True, max_length=500, verbose_name='Plate Number'),
        ),
    ]
